### PR TITLE
Merge bazel-runfiles-server into upstream

### PR DESCRIPTION
**Pull request by Ubehebe**
This PR merges my [bazel-runfiles-server](http://github.com/Ubehebe/bazel-runfiles-server) repo into bazel-watcher. See https://github.com/bazelbuild/bazel-watcher/issues/248 for motivation and further discussion.

Maintainers, how can I help you review this? I've kept the complete commit history from the downstream repo, but can squash if you prefer. I've tried to follow the existing style in both the golang and Starlark sources.

### CODE REVIEW

**Comment by Ubehebe** [comment]
Looks like the Windows tests are failing. The integration test runner waits for the system under test to print a line to its stdout before running the test binary. The line delimiter is [hardcoded](https://github.com/Ubehebe/bazel-watcher/blob/runfiles-server-pr/runfiles_server/integrationtest/integration_test_runner.go#L54) to be `\n`; it probably needs to be `\r` on Windows.

But that's just the proximate cause. The integration test binaries themselves are written in bash and use curl, so I imagine there are plenty of problems ahead. What do you think is the way forward? Ideas:

- Port the tests to Go
- Write .cmd test binaries for Windows
- Disable the Windows tests for this PR and get them working later

**Comment by achew22** [comment]
@Ubehebe, looking through the tests I think my inclination would be to go for the first option, "Port the tests to Go". It looks to me like there are only about 4 tests and they aren't extremely complex. I'd rather push the multi-os compatibility into a language designed for it rather than having 2 or 3 implementations or each test.

**Comment by Ubehebe** [comment]
SGTM. I will be AFK for a few days, but should be able to port the tests by the end of the week.

**Comment by paynecodes** [comment]
@Ubehebe any tips for using this approach today? Other than maintain my own version of ibazel that is :)

**Pull request closed without merging**
