### PR TITLE
automatically increase process ulimit

### PR DESCRIPTION
**Pull request by brendanjryan**
Increases the process `ulimit` to the "hard limit" allowed by the system. This should help remedy the `"Error: too many open files`" error that some users are seeing. 

Related Issues: https://github.com/bazelbuild/bazel-watcher/issues/109

### CODE REVIEW

**Comment by achew22** [comment]
@brendanjryan looks good to me from a code standpoint. I'll be happy to merge once you sign the CLA. Thanks so much for contributing!

**Comment by brendanjryan** [comment]
I signed it!

**Comment by achew22** [comment]
Sorry for the delay in merging this. The CI system changed under the covers and it required some investigation to get the GitHub/BuildKite integration to work again.

Thanks so much for your contribution. I'm going to release a new binary of iBazel to npm later today.

**Comment by brendanjryan** [comment]
@achew22 it's no worries! Thank YOU for maintaining the project 🙇

**Comment by achew22** [comment]
I just cut v0.4.0 right now. Feel free to update from npm or build from source. Thanks again!

**Pull request merged**
