### PR TITLE
Upgrade rules_go and Gazelle

### PR DESCRIPTION
**Pull request by achew22**

### CODE REVIEW

**Comment by kalbasit** [comment]
@achew22 can we get this merged (maybe update rules_go and gazelle to 0.15 first)? I'd like to package this up for [NixOS](https://nixos.org), but I won't be able to until rules_go has been updated.

**Comment by kalbasit** [comment]
@achew22 @alexeagle can we please get this merged?

**Comment by achew22** [comment]
@kalbasit Looks like there might be some issues with the PR.

```
ERROR: error loading package 'third_party/bazel/master/src/main/protobuf': Extension file not found. Unable to load file '@io_bazel_rules_go//proto:go_proto_library.bzl': file doesn't exist or isn't a file
```

Would you be willing to take a look at that? Once CI is green I'm happy to merge

**Comment by kalbasit** [comment]
@achew22 sure, I should have a separate PR up soon.

**Pull request closed without merging**
