### PR TITLE
Update rules_go to 0.7.0

### PR DESCRIPTION
**Pull request by dougkoch**
As an Ubuntu user, I had the same issue with rules_go that @genehwung mentioned in #26. This has since been fixed by https://github.com/bazelbuild/rules_go/pull/850

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by achew22** [comment]
Check this please

**Comment by dougkoch** [comment]
Jenkins, test this please

**Comment by achew22** [comment]
@damienmg, I just added @dougkoch as a contributor to this project. Do I need to do more to whitelist him to run PRs in Jenkins?

**Comment by damienmg** [comment]
Andrew: they need to add 2FA then I can add them to the bazelbuild org and
follow-up

**Comment by dougkoch** [comment]
@damienmg I just enabled 2FA

**Comment by damienmg** [comment]
I invited you to the bazelbuild org, once you accept, go to
https://github.com/orgs/bazelbuild/people?utf8=%E2%9C%93&query=dougkoch and
in front of your name, on the third column, change "Private" to "Public" so
your profile show you are in the bazelbuild org.

Once done so, you will have the power to trigger our CI,  every PR from you
will automatically trigger it and you will be able to trigger it with the
sentence "test this please". Make sure to eyeball a PR for security aspect
before triggering a build.

**Pull request merged**
