### PR TITLE
Enable run_output by default

### PR DESCRIPTION
**Pull request by achew22**
Since run_output_interactive is enabled, it should be safe to prompt the user
if they want to execute the program that was specified by their repo's
`.bazel_fix_commands.json`

### CODE REVIEW

**Comment by achew22** [comment]
@borkaehw + @alexeagle , could I get a sanity check on this? I believe this is safe to enable by default. In the event that you run in an untrusted repo, you would still have to pass `--run_output_interactive=false` in order to be vulnerable. That said, you're already running untrusted code on your computer so you're probably pwned already if you get to this safety check.

**Comment by borkaehw** [comment]
I believe it's safe and nice to have.

**Comment by achew22** [comment]
@alexeagle Is that the case for you as well?

**Comment by achew22** [comment]
@alexeagle, any thoughts on this?

**Comment by alexeagle** [comment]
Sorry I missed the notification - I don't really know how this feature works. "the default path of file should be in the workspace root" - why is there a file at all? Is a compiler tool supposed to create a file when it runs?

I'm certainly in favor of making it easier for compilers to get their fixes applied.

**Comment by achew22** [comment]
@alexeagle interesting, have I misinterpreted the way that the quick fixes are implemented? I was under the impression they were scanning the stderr from the action and if they match some regex then they are executed. Is there a mechanism in a rule to have it emit something that says "The build is broken, please run this command?"

**Comment by borkaehw** [comment]
@achew22 your understanding is correct. The regex is defined in a json file. The rule is responsible to emit the command, if the command matches the regex, run the command.

**Pull request merged**
