### PR TITLE
wait for process to end when killing it

### PR DESCRIPTION
**Pull request by jmhodges**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by achew22** [comment]
I'm not sure how to do this so feel free to push back and say "that's hard and I don't know how to do it either", but is it possible to add a test for this? Are there any standard linux commands (i.e. shipped in busybox) that would exhibit this? I would guess not but I figured I'd ask.

Also -- Jenkins, test this please.

**Comment by jmhodges** [comment]
They'd all be really racy tests. I don't know of any utilities that would reliably delay across OSes. I could do it if we sent SIGTERM instead of SIGKILL

**Comment by achew22** [comment]
I figured. Thanks for the patch!

**Comment by achew22** [comment]
Looks like Travis is having issues with their Mac builds. I'm just going to merge since I can't get the CI to even run for it on Mac.

https://www.traviscistatus.com/incidents/4qylrqvy50gy

**Comment by jmhodges** [comment]
Thank you!

**Pull request merged**
