### PR TITLE
Prepare to publish to NPM:

### PR DESCRIPTION
**Pull request by alexeagle**
Include a binary distribution in the package (only Mac for now)
A wrapper script to fork the native process

Note: the version field on NPM doesn't correspond to anything right now,
I think we should at least tag this repo with a matching version for sanity
We also need some README about performing releases, since no one will remember
when to re-build the binary.

See #15

### CODE REVIEW

**Comment by achew22** [comment]
Alex, just got back from my vacation. This totally looks like the way to go for publishing to NPM. My only hesitation is toward checking in the binaries. Would it bother you if I refer to the `ibazel` binary in the bazel-bin directory and wrapped the uploading in a small bash script?

Do you have any suggestions on owning/managing NPM organizations? Is that the way to go or should I just set it up under a personal account for now?

**Comment by alexeagle** [comment]
"wrapped the uploading" - npm packages are published with the `npm publish` command which expects a directory that contains the artifact tree. We could have a build process that creates such a directory, which would need to be populated with binaries for more platforms over time.

I already have the keys to http://npmjs.com/org/bazel for when we're ready to publish it.

**Comment by achew22** [comment]
Excellent! I sat down and wrote a wrapper for this tonight based on your PR so that we can start publishing to NPM. Do you know what I need to do to make a bazel/ibazel npm package that can be uploaded to?

**Comment by alexeagle** [comment]
`npm login`
tell me your username so I can grant permissions
`npm publish <folder containing package.json>`

**Comment by achew22** [comment]
I think this is probably obviated by #44

**Comment by achew22** [comment]
Closing since #44 landed. Thank you for doing all the hard work on this one!

**Pull request closed without merging**
